# 看板娘 Live2d
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2d-widget/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-shizuku 
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: false

# 首页顶部的全屏大图
# index_img: https://images3.alphacoders.com/100/thumb-1920-1005695.jpg
index_img: https://picfiles.alphacoders.com/257/thumb-1920-257645.jpg
# 文章页、分类页等其他页面的顶部背景图
default_top_img: https://images6.alphacoders.com/129/thumb-1920-1295071.jpg

# 网站小图标
favicon: /favicon.ico